# Generated by Django 5.0.4 on 2024-04-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_pipeline_cmd_alter_result_payload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activescan',
            name='url',
        ),
        migrations.AddField(
            model_name='activescan',
            name='domain',
            field=models.CharField(default='testphp.vulnweb.com', max_length=255),
        ),
        migrations.AddField(
            model_name='activescan',
            name='user',
            field=models.CharField(default='sonic', max_length=100),
        ),
        migrations.AddField(
            model_name='result',
            name='user',
            field=models.CharField(default='sonic', max_length=100),
        ),
    ]
