# Generated by Django 5.0.4 on 2024-05-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_result_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='cybersage', max_length=100)),
                ('domain', models.CharField(default='testphp.vulnweb.com', max_length=255)),
                ('tech_list', models.JSONField()),
                ('waf_info', models.TextField()),
            ],
        ),
    ]
