# Generated by Django 5.0.4 on 2024-05-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='severity',
            field=models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('critical', 'critical')], default='low', max_length=10),
        ),
    ]
