# Generated by Django 5.0.4 on 2024-05-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_pipeline_severity'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='cybersage', max_length=100)),
                ('domain', models.CharField(default='testphp.vulnweb.com', max_length=255)),
                ('CVE', models.CharField(default='', max_length=100)),
                ('Description', models.TextField(default='')),
                ('MaxCVSS', models.CharField(default='', max_length=100)),
                ('EPSS_Score', models.CharField(default='', max_length=100)),
                ('Published', models.CharField(default='', max_length=100)),
                ('Updated', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
