# Generated by Django 5.0.4 on 2024-05-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_networkscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkscan',
            name='SoftwareName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
