# Generated by Django 5.0.4 on 2024-05-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_networkscan_softwarename'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteBoxResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='cybersage', max_length=100)),
                ('domain', models.CharField(default='testphp.vulnweb.com', max_length=255)),
                ('VulnerabilityName', models.CharField(default='', max_length=100)),
                ('VulnerableFilePath', models.CharField(default='', max_length=100)),
                ('VulnerabilityDescription', models.TextField(default='')),
                ('Message', models.CharField(default='', max_length=100)),
                ('StartLine', models.CharField(default='', max_length=100)),
                ('EndLine', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
